FROM python:3.8

RUN adduser -D myuser
USER myuser

WORKDIR /home/myuser/app


COPY ./requirements.txt home/myuser/app
RUN pip install --user --upgrade pip
RUN python3 -m venv venv
RUN pip3 install -r ./requirements.txt

COPY . /app

EXPOSE 80

CMD ["gunicorn", "-b", "0.0.0.0:80", "--timeout", "60000", "app:app"]
