version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-avaialbe/default.conf
    depends_on:
      - web
